"""Research report generator for plagiarism detection benchmarks.

Generates HTML and plain-text reports from benchmark result files.

Usage::

    python scripts/generate_research_report.py \\
        --results-file data/results/benchmark_results.json \\
        --output-dir data/reports \\
        --format both
"""

import argparse
import json
import logging
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict

_SCRIPT_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPT_DIR.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# HTML report
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Plagiarism Detection Research Report</title>
  <style>
    body {{ font-family: Arial, sans-serif; max-width: 960px; margin: 40px auto;
            padding: 0 20px; color: #333; line-height: 1.6; }}
    h1 {{ color: #1a1a2e; border-bottom: 3px solid #4a90d9; padding-bottom: 10px; }}
    h2 {{ color: #16213e; border-bottom: 1px solid #ccc; padding-bottom: 5px; }}
    table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
    th {{ background: #4a90d9; color: white; padding: 10px 14px; text-align: left; }}
    td {{ border: 1px solid #ddd; padding: 8px 14px; }}
    tr:nth-child(even) {{ background: #f9f9f9; }}
    .metric-good {{ color: #27ae60; font-weight: bold; }}
    .metric-poor {{ color: #c0392b; font-weight: bold; }}
    .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px;
              background: #eaf3fb; color: #2980b9; font-size: 0.85em; }}
    pre {{ background: #f4f4f4; padding: 14px; border-radius: 6px;
           overflow-x: auto; font-size: 0.9em; }}
    footer {{ margin-top: 40px; color: #777; font-size: 0.85em;
              border-top: 1px solid #eee; padding-top: 12px; }}
  </style>
</head>
<body>
  <h1>Plagiarism Detection Research Report</h1>
  <p><strong>Generated:</strong> {generated_at}</p>
  <p><strong>Corpus:</strong> {corpus_dir}</p>
  <p><strong>Document pairs evaluated:</strong> {total_pairs}
     ({plagiarised_pairs} plagiarised)</p>

  <h2>Methodology</h2>
  <p>This report evaluates five plagiarism detection algorithms on a PAN-style
  corpus.  Each algorithm produces a continuous similarity score; a binary
  prediction is obtained by thresholding at the algorithm's configured value.
  Standard classification metrics (Precision, Recall, F1, Accuracy, AUC-ROC)
  are reported for each algorithm.</p>
  <ul>
    <li><strong>TF-IDF:</strong> TF-IDF cosine similarity baseline.</li>
    <li><strong>S-BERT:</strong> Semantic similarity via Sentence-BERT embeddings.</li>
    <li><strong>N-Gram:</strong> Character n-gram Jaccard similarity.</li>
    <li><strong>Word-Embedding:</strong> TF-IDF weighted document vector cosine similarity.</li>
    <li><strong>Ensemble:</strong> Weighted combination of TF-IDF, S-BERT and N-Gram.</li>
  </ul>

  <h2>Results</h2>
  {results_table}

  <h2>Algorithm Details</h2>
  {algorithm_details}

  <footer>
    Generated by the Plagiarism Detection Research Toolkit &mdash;
    <a href="https://pan.webis.de/">PAN Shared Tasks</a>
  </footer>
</body>
</html>
"""


def _make_html_table(algorithms: Dict[str, Dict[str, Any]]) -> str:
    """Render the algorithm metrics as an HTML table."""
    if not algorithms:
        return "<p>No algorithm results available.</p>"

    all_metrics = ["accuracy", "precision", "recall", "f1", "roc_auc", "elapsed_seconds"]
    present = [m for m in all_metrics if any(m in v for v in algorithms.values())]

    headers = "".join(f"<th>{m.replace('_', ' ').upper()}</th>" for m in present)
    rows = []
    for algo_name, metrics in algorithms.items():
        cells = [f"<td><strong>{algo_name}</strong></td>"]
        for m in present:
            val = metrics.get(m)
            if val is None:
                cells.append("<td>N/A</td>")
            elif m == "elapsed_seconds":
                cells.append(f"<td>{val:.2f}s</td>")
            else:
                css = ""
                if m == "f1":
                    css = "metric-good" if val >= 0.75 else ("metric-poor" if val < 0.5 else "")
                cells.append(f'<td class="{css}">{val:.4f}</td>' if css else f"<td>{val:.4f}</td>")
        rows.append(f"<tr>{''.join(cells)}</tr>")

    return (
        f"<table><thead><tr><th>Algorithm</th>{headers}</tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table>"
    )


def _make_html_details(algorithms: Dict[str, Dict[str, Any]]) -> str:
    """Render per-algorithm metric cards."""
    if not algorithms:
        return ""
    parts = []
    for algo_name, metrics in algorithms.items():
        items = "".join(
            f"<li><strong>{k}:</strong> {v}</li>"
            for k, v in sorted(metrics.items())
        )
        parts.append(f"<h3>{algo_name}</h3><ul>{items}</ul>")
    return "\n".join(parts)


def generate_html_report(results: Dict, output_path: str) -> None:
    """Generate a comprehensive HTML research report.

    Args:
        results: Benchmark results dict (output of ``run_benchmark``).
        output_path: File path to write the HTML report.
    """
    algorithms = results.get("algorithms", {})
    html = _HTML_TEMPLATE.format(
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        corpus_dir=results.get("corpus_dir", "N/A"),
        total_pairs=results.get("total_pairs", 0),
        plagiarised_pairs=results.get("plagiarised_pairs", 0),
        results_table=_make_html_table(algorithms),
        algorithm_details=_make_html_details(algorithms),
    )
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(html, encoding="utf-8")
    logger.info("HTML report written to %s", output_path)
    print(f"HTML report saved: {output_path}")


# ---------------------------------------------------------------------------
# Plain-text report
# ---------------------------------------------------------------------------

def generate_text_report(results: Dict, output_path: str) -> None:
    """Generate a plain-text research report.

    Args:
        results: Benchmark results dict.
        output_path: File path to write the text report.
    """
    lines = [
        "=" * 70,
        "PLAGIARISM DETECTION RESEARCH REPORT",
        "=" * 70,
        f"Generated : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"Corpus    : {results.get('corpus_dir', 'N/A')}",
        f"Pairs     : {results.get('total_pairs', 0)} "
        f"({results.get('plagiarised_pairs', 0)} plagiarised)",
        "",
        "METHODOLOGY",
        "-" * 70,
        (
            "Algorithms are evaluated with standard classification metrics.\n"
            "Similarity scores are thresholded to produce binary predictions."
        ),
        "",
        "RESULTS",
        "-" * 70,
    ]

    algorithms = results.get("algorithms", {})
    all_metrics = ["accuracy", "precision", "recall", "f1", "roc_auc", "elapsed_seconds"]
    present = [m for m in all_metrics if any(m in v for v in algorithms.values())]

    col = 14
    header = f"{'Algorithm':<18}" + "".join(f"{m.upper():>{col}}" for m in present)
    lines.append(header)
    lines.append("-" * len(header))

    for algo_name, metrics in algorithms.items():
        row = f"{algo_name:<18}"
        for m in present:
            val = metrics.get(m)
            if val is None:
                row += f"{'N/A':>{col}}"
            elif m == "elapsed_seconds":
                row += f"{val:>{col}.2f}s"[: col + 1].rjust(col)
            else:
                row += f"{val:>{col}.4f}"
        lines.append(row)

    lines += [
        "-" * len(header),
        "",
        "ALGORITHM DESCRIPTIONS",
        "-" * 70,
        "TF-IDF        : TF-IDF cosine similarity baseline.",
        "S-BERT        : Sentence-BERT semantic embedding similarity.",
        "N-Gram        : Character n-gram Jaccard similarity.",
        "Word-Embedding: TF-IDF weighted document vector cosine similarity.",
        "Ensemble      : Weighted combination of TF-IDF, S-BERT and N-Gram.",
        "",
        "REFERENCES",
        "-" * 70,
        "PAN Shared Tasks: https://pan.webis.de/",
        "sentence-transformers: https://www.sbert.net/",
        "scikit-learn: https://scikit-learn.org/",
        "=" * 70,
    ]

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text("\n".join(lines), encoding="utf-8")
    logger.info("Text report written to %s", output_path)
    print(f"Text report saved: {output_path}")


# ---------------------------------------------------------------------------
# Loader
# ---------------------------------------------------------------------------

def load_benchmark_results(results_file: str) -> Dict:
    """Load benchmark results from a JSON file.

    Args:
        results_file: Path to the JSON results file.

    Returns:
        Results dict.
    """
    path = Path(results_file)
    if not path.exists():
        raise FileNotFoundError(f"Results file not found: {results_file}")
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    """CLI entry point for report generation."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )

    parser = argparse.ArgumentParser(
        description="Generate a research report from benchmark results.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/generate_research_report.py \\
      --results-file data/results/benchmark_results.json \\
      --output-dir data/reports \\
      --format both
""",
    )
    parser.add_argument(
        "--results-file",
        default="data/results/benchmark_results.json",
        help="Path to the benchmark JSON results file.",
    )
    parser.add_argument(
        "--output-dir",
        default="data/reports",
        help="Directory for output report files.",
    )
    parser.add_argument(
        "--format",
        choices=["html", "text", "both"],
        default="both",
        help="Output format (default: both).",
    )

    args = parser.parse_args()

    try:
        results = load_benchmark_results(args.results_file)
    except FileNotFoundError as exc:
        print(f"ERROR: {exc}")
        print("Run 'python scripts/run_benchmarks.py' first to generate results.")
        sys.exit(1)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if args.format in ("html", "both"):
        generate_html_report(results, str(output_dir / "research_report.html"))

    if args.format in ("text", "both"):
        generate_text_report(results, str(output_dir / "research_report.txt"))


if __name__ == "__main__":
    main()
